Vehicle_Response = [
    [
    "0",
    "B",
],
    [
    "A",
    "C",
],
    [
    "B",
    "F",
],
    [
    "C",
    "E",
],
    [
    "D",
    "F",
],
    [
    "C",
    "1",
],
]
vehicle_name = "A"
vehicles = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
]
